runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /scss
  static_dir: scss

- url: /vendor
  static_dir: vendor

- url: /
  script: index.php

- utl: /index.html
  script: index.html
  
- url: /careers
  script: careers.php

- url: /careers.html
  script: careers.html

- url: /jobs-form.html
  script: jobs-form.html

- url: /jobs-form
  script: jobs-form.php

- url: /direct_upload
  script: direct_upload.php

- url: /handle_upload
  script: handle_upload.php

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /favicon-32x32\.png
  static_files: favicon-32x32.png
  upload: favicon-32x32\.png
  
- url: /android-chrome-144x144\.png
  static_files: android-chrome-144x144.png
  upload: android-chrome-144x144\.png
  
- url: /favicon-16x16\.png
  static_files: favicon-16x16.png
  upload: favicon-16x16\.png

- url: /.*
  script: index.php
