runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /scss
  static_dir: scss

- url: /vendor
  static_dir: vendor

- url: /
  script: index.html
  secure: always

- url: /index.html
  script: index.html
  secure: always
  
- url: /careers
  script: careers.html
  secure: always

- url: /career
  script: careers.html
  secure: always

- url: /careers.html
  script: careers.html

- url: /job.html
  script: job.htm
  secure: always

- url: /job
  script: job.html
  secure: always

- url: /jobs
  script: job.html
  secure: always

- url: /admission.html
  script: admission.html
  secure: always

- url: /admission
  script: admission.html
  secure: always

- url: /admissions
  script: admission.html
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /favicon\-32x32\.png
  static_files: favicon-32x32.png
  upload: favicon\-32x32\.png

- url: /apple\-touch\-icon\.png
  static_files: apple-touch-icon.png
  upload: apple\-touch\-icon\.png

- url: /android\-chrome\-144x144\.png
  static_files: android-chrome-144x144.png
  upload: android\-chrome\-144x144\.png

- url: /mstile\-150x150\.png
  static_files: mstile-150x150.png
  upload: mstile\-150x150\.png

- url: /safari\-pinned\-tab\.svg
  static_files: safari-pinned-tab.svg
  upload: safari\-pinned\-tab\.svg

- url: /.*
  script: index.html
  secure: always
